import { PageHeader, Card, CardTitle, Stat } from "@/components/ui";

export default function GeneratedPage() {
  return (
    <div>
      <PageHeader title="A futuristic, high-tech UI/UX dashboard " description="Generated by NOVA (mock mode)." />
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        <Stat label="Metric A" value="1,280" sub="+4.2%" subColor="text-emerald-400" />
        <Stat label="Metric B" value="312" sub="today" />
        <Stat label="Metric C" value="98%" />
        <Stat label="Metric D" value="$4.3k" />
      </div>
      <Card>
        <CardTitle>Request</CardTitle>
        <p className="text-sm text-(--color-muted)">A futuristic, high-tech UI/UX dashboard design, inspired by the Yggdrasil World Tree. In the center, a glowing holographic cyber-organic cosmic tree with intricate glowing roots and branches. The tree has 9 distinct major branches, each branching out to represent a different AI domain (AI Nodes/Realms), stylized with sleek tech layout frames and data visualizations. Each of the 9 nodes features a unique glowing neon icon and futuristic data widgets (graphs, binary code streams, progress bars, circuit board patterns). Dark sleek metallic background, deep obsidian and midnight blue tones, contrasted with vibrant cyan, emerald green, and ethereal gold neon bioluminescent lights. FUI (Futuristic User Interface) style, clean layout, highly detailed, 8k resolution, cinematic lighting, cyberpunk-fantasy aesthetic

Team brief (turn this into real Next.js files):
[LUNA] [mock] LUNA completed: Design the UX/UI for the request
[NOVA] [mock] NOVA completed: Build the frontend from the design</p>
      </Card>
    </div>
  );
}
