// Runs the decile study on the cached daily bars and prints the gate report for
// both pre-registered legs. This file owns every impure thing the module is
// forbidden: reading the cache, printing, and writing the results doc.
//
// Usage: npx tsx scripts/decile-momentum-study.mts
import { readFile, mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { alignUniverse } from "@/lib/backtest/crossSectional/calendar";
import { evaluateGates } from "@/lib/backtest/crossMomentum/gates";
import { buildSnapshots, subsetBars, topByDollarVolume } from "@/lib/backtest/crossMomentum/study";
import {
  screenBars,
  MIN_DAILY_RATIO,
  MAX_DAILY_RATIO,
  MAX_ZERO_VOLUME_SHARE,
  MAX_MEDIAN_SPACING_DAYS,
} from "@/lib/backtest/crossMomentum/dataQuality";
import type { MomentumConfig, ScoreLeg } from "@/lib/backtest/crossMomentum/types";
import type { Candle } from "@/lib/indicators";

const CACHE = ".cache/bars/sp500-1d.json";
const OUT = "docs/quant/2026-08-16-cross-sectional-momentum-results.md";
const MEGA_CAP_COUNT = 200;
const DOLLAR_VOL_WINDOW = 63;
/** Set by hand, not read from the clock, so a re-run of the same cache is reproducible. */
const RUN_DATE = "2026-08-17";

const cfg: MomentumConfig = {
  lookback: 252,
  skip: 21,
  buckets: 10,
  minEligible: 100,
  costBps: 5,
  seed: 20_260_816,
  iterations: 1_000,
  blocks: 6,
};

const raw = JSON.parse(await readFile(CACHE, "utf8")) as { fetchedAt: string; bars: Record<string, Candle[]> };
const cached = new Map(Object.entries(raw.bars));
// SPY is an index proxy, not a cross-section member.
cached.delete("SPY");

// Screen before anything is measured. Alpaca's `adjustment=all` is provably
// incomplete for recent splits, so the cache cannot be trusted blindly even
// after the provider fixes; see crossMomentum/dataQuality.ts.
const { kept: bars, excluded } = screenBars(cached);
if (bars.size === 0) throw new Error("data screen rejected every symbol — check the cache");

const iso = (day: number) => new Date(day * 86_400_000).toISOString().slice(0, 10);

const full = buildSnapshots(bars, cfg);
if (full.snapshots.length === 0) throw new Error("no rebalance dates produced — check the cache");

const { days, index } = alignUniverse(bars);
// A backfilled membership list is not a rectangle: names list late (IPOs,
// spinoffs) and stop early (acquisitions). Those are properties of the universe,
// not holes in the cache, and the fill/exit logic exists to handle them.
const lateStarts = [...index.values()].filter((m) => ![...m.keys()].includes(days[0])).length;
const earlyEnds = [...index.values()].filter((m) => ![...m.keys()].includes(days[days.length - 1])).length;
const megaSymbols = topByDollarVolume(bars, days, full.snapshots[0].day, DOLLAR_VOL_WINDOW, MEGA_CAP_COUNT);
const mega = buildSnapshots(subsetBars(bars, megaSymbols), cfg);

const legs: ScoreLeg[] = ["raw", "volAdj"];
const reports = legs.map((leg) =>
  evaluateGates({ leg, snapshots: full.snapshots, megaCapSnapshots: mega.snapshots, cfg }),
);

const pct = (x: number) => `${(x * 100).toFixed(3)}%`;
const yn = (b: boolean) => (b ? "**PASS**" : "**FAIL**");

const lines: string[] = [
  "# Cross-Sectional Momentum — Decile Study Results",
  "",
  `**Run date:** ${RUN_DATE} · **Cache fetched:** ${raw.fetchedAt}`,
  `**Spec:** \`docs/superpowers/specs/2026-08-16-cross-sectional-momentum-design.md\``,
  "",
  "This is a diagnostic, not a strategy. The strongest outcome available is NOT REJECTED.",
  "",
  "> Everything above the `## Verdict` heading below is machine-generated by",
  "> `scripts/decile-momentum-study.mts`. Re-running that script overwrites this entire file with",
  "> `writeFile`, including the `## Verdict` section — the script has no knowledge that section",
  "> exists. Do not re-run it after the verdict has been written; if the study needs to be re-run,",
  "> copy the verdict out first and reconcile it by hand afterward.",
  "",
  "## This run is not blind",
  "",
  "The first run of this study (2026-08-16) was voided: its cache held unadjusted split prices, which",
  "load genuine winners into the loser bucket and drive the decile spread negative by construction.",
  "Three data defects were found and fixed — Yahoo ignored `adjclose`, Alpaca defaulted to",
  "`adjustment=raw`, and Alpaca's free `iex` feed has multi-month holes. The author of this re-run has",
  "therefore already seen one set of gate results for the same hypothesis on the same universe. The",
  "hypothesis, the six gates, and the thresholds are unchanged from the pre-registration — but a",
  "re-run by someone who has seen a prior outcome is weaker evidence than a blind one, and nothing",
  "here should be read as if it were blind.",
  "",
  "The screen below also ran twice, and the first version of it is disclosed here so the sequence is",
  "not mistaken for tuning. Rules 2-4 were written and committed before any post-fix numbers existed;",
  "that screen dropped 12 of 490 symbols and produced **Leg A: REJECTED** (ρ 0.248, p 0.0559) and",
  "**Leg B: REJECTED** (ρ 0.515, p 0.2058). Auditing the calendar of that run then showed that 37",
  "union-calendar days were market holidays contributed by a single symbol, DOW, whose series came",
  "back from the provider as weekly bars; one of those holidays, 2021-05-31, had become a rebalance",
  "date. Rule 1 was added to catch that class and the study re-run. The trigger was a defective",
  "calendar, not a disappointing gate — but the reader is entitled to both sets of numbers.",
  "",
  "## Data screen (stated before the results)",
  "",
  "Alpaca's `adjustment=all` is incomplete for recent splits: KLAC split 10:1 on 2026-06-12 and the",
  "feed still reports 2411.64 → 254.54, while Yahoo's `adjclose` shows a smooth 241.16 → 254.54 with",
  "every post-split bar agreeing exactly. So the cache is screened rather than trusted. A symbol is",
  "excluded from the study entirely — not for one month — when any of these holds:",
  "",
  `1. its bars are spaced more than ${MAX_MEDIAN_SPACING_DAYS} calendar days apart at the median — i.e. it is not a daily series;`,
  `2. any close is zero or negative;`,
  `3. any adjacent-session close ratio falls outside [${MIN_DAILY_RATIO}, ${MAX_DAILY_RATIO}];`,
  `4. at least ${(MAX_ZERO_VOLUME_SHARE * 100).toFixed(0)}% of its bars have zero volume (a placeholder or reused-ticker series).`,
  "",
  "Whole-symbol, because a contaminated bar spoils every 252-day window that crosses it — a year of",
  "rebalances — not just the month it sits in. Rule 2 also removes genuine one-day collapses, which is",
  "a real cost; but an excluded symbol leaves the winner and loser buckets alike, so the exclusion has",
  "no known directional effect on the spread, unlike split contamination.",
  "",
  `**${excluded.length} of ${cached.size} symbols excluded.**`,
  "",
  ...(excluded.length === 0
    ? ["_(none)_", ""]
    : [
        "| Symbol | Reason | Evidence |",
        "|---|---|---|",
        ...excluded.map((e) => `| ${e.symbol} | ${e.reason} | ${e.detail} |`),
        "",
      ]),
  "## Sample",
  "",
  `- symbols: ${bars.size}`,
  `- rebalances: **${full.snapshots.length}** (${iso(full.snapshots[0].day)} → ${iso(full.snapshots[full.snapshots.length - 1].day)})`,
  `- eligible per rebalance: min ${Math.min(...full.snapshots.map((s) => s.symbols.length))}, max ${Math.max(...full.snapshots.map((s) => s.symbols.length))}`,
  `- fill/exit substitutions: ${full.substitutions} (${pct(full.substitutions / full.snapshots.reduce((n, s) => n + s.symbols.length, 0))} of symbol-months — see "Reading these numbers" below)`,
  `- unfillable selections (dropped, no measurable return): ${full.unfillable}`,
  `- mega-cap subset: ${megaSymbols.size} symbols, ${mega.snapshots.length} rebalances`,
  `- config: lookback ${cfg.lookback}, skip ${cfg.skip}, buckets ${cfg.buckets}, seed ${cfg.seed}, ${cfg.iterations} permutations`,
  "",
];

for (const r of reports) {
  lines.push(
    `## Leg ${r.leg === "raw" ? "A — classic 12-1" : "B — volatility-adjusted"}`,
    "",
    `### Verdict: ${r.passed ? "**NOT REJECTED**" : "**REJECTED**"}`,
    "",
    "| # | Gate | Value | Threshold | Result |",
    "|---|---|---|---|---|",
    `| 1 | Monotonicity (Spearman ρ) | ${r.monotonicity.rho.toFixed(3)} | ≥ 0.60 | ${yn(r.monotonicity.pass)} |`,
    `| 2 | Permutation p | ${r.permutation.p.toFixed(4)} | ≤ 0.05 | ${yn(r.permutation.pass)} |`,
    `| 3 | Other leg's mean spread | ${pct(r.crossDefinition.otherMeanSpread)} | > 0 | ${yn(r.crossDefinition.pass)} |`,
    `| 4 | Bottom bucket vs universe ex-top | ${pct(r.notTopOnly.meanShortLegExcess)} | > 0 | ${yn(r.notTopOnly.pass)} |`,
    `| 5 | Mega-cap mean spread | ${pct(r.megaCap.meanSpread)} | > 0 | ${yn(r.megaCap.pass)} |`,
    `| 6 | Positive sub-periods | ${r.subPeriods.positive} of ${r.subPeriods.of} | ≥ 4 | ${yn(r.subPeriods.pass)} |`,
    "",
    "Reported, not gated:",
    "",
    `- mean monthly spread: **${pct(r.meanSpread)}** (net of 5 bps/side: ${pct(r.netMeanSpread)})`,
    `- t-statistic: **${r.tStat.toFixed(2)}** over ${r.months} months`,
    `- mean turnover per rebalance: ${pct(r.meanTurnover)}`,
    `- bucket means (1 = losers → ${cfg.buckets} = winners): ${r.bucketMeans.map((x) => pct(x)).join(", ")}`,
    `- sub-period means: ${r.subPeriods.blockMeans.map((x) => pct(x)).join(", ")}`,
    "",
  );
  console.log(`${r.leg}: ${r.passed ? "NOT REJECTED" : "REJECTED"}  rho=${r.monotonicity.rho.toFixed(3)} p=${r.permutation.p.toFixed(4)} spread=${pct(r.meanSpread)} t=${r.tStat.toFixed(2)}`);
}

lines.push(
  "## Reading these numbers",
  "",
  `At ${full.snapshots.length} monthly observations, \`t = 2\` requires an annual Sharpe near 0.90, while`,
  "published momentum decile spreads run 0.5-0.6 over far longer samples. The t-statistic above is",
  "therefore reported for reference and is not one of the gates. A leg marked NOT REJECTED has cleared",
  "six pre-registered hurdles on a short sample; it has not been validated.",
  "",
  "The universe is the **current** S&P 500 membership backfilled, so it is survivorship-biased in the",
  "direction that manufactures momentum. Gates 4 and 5 exist to test that explanation directly.",
  "",
  `The union calendar holds ${days.length} trading days. Of the ${bars.size} surviving symbols, ${lateStarts} have no bar on the`,
  `first day and ${earlyEnds} have none on the last: a backfilled membership list is not a rectangle, because`,
  "names list late (IPOs, spinoffs) and stop early (acquisitions — JNPR, ANSS, HES, DFS and DAY all",
  "left the tape inside this window). The fill/exit logic covers those, and the unfillable count above",
  "is the number of selections that could not be measured at all.",
  "",
  "The substitution count above is the pre-registered check on that logic, and it now sits in the",
  "single digits. It did not on the first screened run — 4,701 substitutions, 9% of symbol-months —",
  "which is what led to the DOW discovery described at the top: one weekly series had injected 37",
  "market holidays into the union calendar, so on each of those days every other symbol needed a fill.",
  "",
);

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, lines.join("\n"));
console.log(`\nwrote ${OUT}`);
