// Runs the decile study on the cached daily bars and prints the gate report for
// both pre-registered legs. This file owns every impure thing the module is
// forbidden: reading the cache, printing, and writing the results doc.
//
// Usage: npx tsx scripts/decile-momentum-study.mts
import { readFile, mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { alignUniverse } from "@/lib/backtest/crossSectional/calendar";
import { evaluateGates } from "@/lib/backtest/crossMomentum/gates";
import { buildSnapshots, subsetBars, topByDollarVolume } from "@/lib/backtest/crossMomentum/study";
import type { MomentumConfig, ScoreLeg } from "@/lib/backtest/crossMomentum/types";
import type { Candle } from "@/lib/indicators";

const CACHE = ".cache/bars/sp500-1d.json";
const OUT = "docs/quant/2026-08-16-cross-sectional-momentum-results.md";
const MEGA_CAP_COUNT = 200;
const DOLLAR_VOL_WINDOW = 63;

const cfg: MomentumConfig = {
  lookback: 252,
  skip: 21,
  buckets: 10,
  minEligible: 100,
  costBps: 5,
  seed: 20_260_816,
  iterations: 1_000,
  blocks: 6,
};

const raw = JSON.parse(await readFile(CACHE, "utf8")) as { fetchedAt: string; bars: Record<string, Candle[]> };
const bars = new Map(Object.entries(raw.bars));
// SPY is an index proxy, not a cross-section member.
bars.delete("SPY");

const iso = (day: number) => new Date(day * 86_400_000).toISOString().slice(0, 10);

const full = buildSnapshots(bars, cfg);
if (full.snapshots.length === 0) throw new Error("no rebalance dates produced — check the cache");

const { days } = alignUniverse(bars);
const megaSymbols = topByDollarVolume(bars, days, full.snapshots[0].day, DOLLAR_VOL_WINDOW, MEGA_CAP_COUNT);
const mega = buildSnapshots(subsetBars(bars, megaSymbols), cfg);

const legs: ScoreLeg[] = ["raw", "volAdj"];
const reports = legs.map((leg) =>
  evaluateGates({ leg, snapshots: full.snapshots, megaCapSnapshots: mega.snapshots, cfg }),
);

const pct = (x: number) => `${(x * 100).toFixed(3)}%`;
const yn = (b: boolean) => (b ? "**PASS**" : "**FAIL**");

const lines: string[] = [
  "# Cross-Sectional Momentum — Decile Study Results",
  "",
  `**Run date:** 2026-08-16 · **Cache fetched:** ${raw.fetchedAt}`,
  `**Spec:** \`docs/superpowers/specs/2026-08-16-cross-sectional-momentum-design.md\``,
  "",
  "This is a diagnostic, not a strategy. The strongest outcome available is NOT REJECTED.",
  "",
  "> Everything above the `## Verdict` heading below is machine-generated by",
  "> `scripts/decile-momentum-study.mts`. Re-running that script overwrites this entire file with",
  "> `writeFile`, including the `## Verdict` section — the script has no knowledge that section",
  "> exists. Do not re-run it after the verdict has been written; if the study needs to be re-run,",
  "> copy the verdict out first and reconcile it by hand afterward.",
  "",
  "## Sample",
  "",
  `- symbols: ${bars.size}`,
  `- rebalances: **${full.snapshots.length}** (${iso(full.snapshots[0].day)} → ${iso(full.snapshots[full.snapshots.length - 1].day)})`,
  `- eligible per rebalance: min ${Math.min(...full.snapshots.map((s) => s.symbols.length))}, max ${Math.max(...full.snapshots.map((s) => s.symbols.length))}`,
  `- fill/exit substitutions: ${full.substitutions} (${pct(full.substitutions / full.snapshots.reduce((n, s) => n + s.symbols.length, 0))} of symbol-months — see "Reading these numbers" below)`,
  `- unfillable selections (dropped, no measurable return): ${full.unfillable}`,
  `- mega-cap subset: ${megaSymbols.size} symbols, ${mega.snapshots.length} rebalances`,
  `- config: lookback ${cfg.lookback}, skip ${cfg.skip}, buckets ${cfg.buckets}, seed ${cfg.seed}, ${cfg.iterations} permutations`,
  "",
];

for (const r of reports) {
  lines.push(
    `## Leg ${r.leg === "raw" ? "A — classic 12-1" : "B — volatility-adjusted"}`,
    "",
    `### Verdict: ${r.passed ? "**NOT REJECTED**" : "**REJECTED**"}`,
    "",
    "| # | Gate | Value | Threshold | Result |",
    "|---|---|---|---|---|",
    `| 1 | Monotonicity (Spearman ρ) | ${r.monotonicity.rho.toFixed(3)} | ≥ 0.60 | ${yn(r.monotonicity.pass)} |`,
    `| 2 | Permutation p | ${r.permutation.p.toFixed(4)} | ≤ 0.05 | ${yn(r.permutation.pass)} |`,
    `| 3 | Other leg's mean spread | ${pct(r.crossDefinition.otherMeanSpread)} | > 0 | ${yn(r.crossDefinition.pass)} |`,
    `| 4 | Bottom bucket vs universe ex-top | ${pct(r.notTopOnly.meanShortLegExcess)} | > 0 | ${yn(r.notTopOnly.pass)} |`,
    `| 5 | Mega-cap mean spread | ${pct(r.megaCap.meanSpread)} | > 0 | ${yn(r.megaCap.pass)} |`,
    `| 6 | Positive sub-periods | ${r.subPeriods.positive} of ${r.subPeriods.of} | ≥ 4 | ${yn(r.subPeriods.pass)} |`,
    "",
    "Reported, not gated:",
    "",
    `- mean monthly spread: **${pct(r.meanSpread)}** (net of 5 bps/side: ${pct(r.netMeanSpread)})`,
    `- t-statistic: **${r.tStat.toFixed(2)}** over ${r.months} months`,
    `- mean turnover per rebalance: ${pct(r.meanTurnover)}`,
    `- bucket means (1 = losers → ${cfg.buckets} = winners): ${r.bucketMeans.map((x) => pct(x)).join(", ")}`,
    `- sub-period means: ${r.subPeriods.blockMeans.map((x) => pct(x)).join(", ")}`,
    "",
  );
  console.log(`${r.leg}: ${r.passed ? "NOT REJECTED" : "REJECTED"}  rho=${r.monotonicity.rho.toFixed(3)} p=${r.permutation.p.toFixed(4)} spread=${pct(r.meanSpread)} t=${r.tStat.toFixed(2)}`);
}

lines.push(
  "## Reading these numbers",
  "",
  `At ${full.snapshots.length} monthly observations, \`t = 2\` requires an annual Sharpe near 0.90, while`,
  "published momentum decile spreads run 0.5-0.6 over far longer samples. The t-statistic above is",
  "therefore reported for reference and is not one of the gates. A leg marked NOT REJECTED has cleared",
  "six pre-registered hurdles on a short sample; it has not been validated.",
  "",
  "The universe is the **current** S&P 500 membership backfilled, so it is survivorship-biased in the",
  "direction that manufactures momentum. Gates 4 and 5 exist to test that explanation directly.",
  "",
  "The fill/exit substitution count above was checked against the pre-registered expectation of a",
  "single-digit count and found far higher. Investigation (per-symbol bar-date ranges, day-by-day",
  "union-calendar coverage) traced this to the cache itself: `.cache/bars/sp500-1d.json` has scattered,",
  "mostly single-day gaps spread across nearly the whole symbol set — 490 symbols but only 54 of 1,639",
  "union calendar days have a bar from every symbol. A small number of names (about a dozen, e.g. BK,",
  "CTRA, DFS, HOLX, JNPR, K, MMC) stop receiving bars months before the cache's stated fetch date despite",
  "still being live, currently-traded tickers, not delistings. This is a data-completeness property of",
  "the cache, not a defect in `buildSnapshots`: the fill logic (exit at the last available open) and the",
  "unfillable count (1, matching the pre-registered expectation) behave exactly as designed given an",
  "imperfect feed. It does not change the gate results, since gates operate on realized returns, not on",
  "whether a return's bar landed on the exact intended day — but it means this run's substitution count",
  "is a statement about the cache's completeness, not about the study.",
  "",
);

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, lines.join("\n"));
console.log(`\nwrote ${OUT}`);
