// scripts/decile-momentum-study-pointintime-rerun.mts
// Point-in-time re-run of scripts/decile-momentum-study.mts: identical
// config, gates, and universe cache — the only change is that buildSnapshots
// is gated on real point-in-time S&P 500 membership instead of today's
// static list. The original script and its results doc
// (docs/quant/2026-08-16-cross-sectional-momentum-results.md) are left
// untouched, matching that script's own warning against overwriting a
// written verdict.
//
// Usage: npx tsx scripts/decile-momentum-study-pointintime-rerun.mts
import { readFile, mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { alignUniverse } from "@/lib/backtest/crossSectional/calendar";
import { parseMembershipCsv, buildMembershipIndex } from "@/lib/backtest/crossSectional/membership";
import { evaluateGates } from "@/lib/backtest/crossMomentum/gates";
import { buildSnapshots, subsetBars, topByDollarVolume } from "@/lib/backtest/crossMomentum/study";
import {
  screenBars,
  MIN_DAILY_RATIO,
  MAX_DAILY_RATIO,
  MAX_ZERO_VOLUME_SHARE,
  MAX_MEDIAN_SPACING_DAYS,
} from "@/lib/backtest/crossMomentum/dataQuality";
import type { MomentumConfig, ScoreLeg } from "@/lib/backtest/crossMomentum/types";
import type { Candle } from "@/lib/indicators";

const CACHE = ".cache/bars/sp500-1d.json";
const MEMBERSHIP_CACHE = ".cache/sp500-membership.csv";
const OUT = "docs/quant/2026-08-18-cross-sectional-momentum-pointintime-rerun.md";
const MEGA_CAP_COUNT = 200;
const DOLLAR_VOL_WINDOW = 63;
/** Set by hand, not read from the clock, so a re-run of the same cache is reproducible. */
const RUN_DATE = "2026-08-18";

// Identical to the original study's config — same lookback, skip, buckets,
// seed, iterations, blocks. Only the universe changes.
const cfg: MomentumConfig = {
  lookback: 252,
  skip: 21,
  buckets: 10,
  minEligible: 100,
  costBps: 5,
  seed: 20_260_816,
  iterations: 1_000,
  blocks: 6,
};

const raw = JSON.parse(await readFile(CACHE, "utf8")) as { fetchedAt: string; bars: Record<string, Candle[]> };
const cached = new Map(Object.entries(raw.bars));
// SPY is an index proxy, not a cross-section member.
cached.delete("SPY");

const isMember = buildMembershipIndex(parseMembershipCsv(await readFile(MEMBERSHIP_CACHE, "utf8")));

// Screen before anything is measured — same screen as the original study.
const { kept: bars, excluded } = screenBars(cached);
if (bars.size === 0) throw new Error("data screen rejected every symbol — check the cache");

const iso = (day: number) => new Date(day * 86_400_000).toISOString().slice(0, 10);

const full = buildSnapshots(bars, cfg, isMember);
if (full.snapshots.length === 0) throw new Error("no rebalance dates produced — check the cache");

const { days, index } = alignUniverse(bars);
const lateStarts = [...index.values()].filter((m) => ![...m.keys()].includes(days[0])).length;
const earlyEnds = [...index.values()].filter((m) => ![...m.keys()].includes(days[days.length - 1])).length;
const megaSymbols = topByDollarVolume(bars, days, full.snapshots[0].day, DOLLAR_VOL_WINDOW, MEGA_CAP_COUNT);
const mega = buildSnapshots(subsetBars(bars, megaSymbols), cfg, isMember);

const legs: ScoreLeg[] = ["raw", "volAdj"];
const reports = legs.map((leg) =>
  evaluateGates({ leg, snapshots: full.snapshots, megaCapSnapshots: mega.snapshots, cfg }),
);

const pct = (x: number) => `${(x * 100).toFixed(3)}%`;
const yn = (b: boolean) => (b ? "**PASS**" : "**FAIL**");

const lines: string[] = [
  "# Cross-Sectional Momentum — Point-in-Time Membership Re-run",
  "",
  `**Run date:** ${RUN_DATE} · **Cache fetched:** ${raw.fetchedAt}`,
  `**Spec:** \`docs/superpowers/specs/2026-08-18-point-in-time-membership-design.md\``,
  "",
  "This is a diagnostic, not a strategy. The strongest outcome available is NOT REJECTED.",
  "",
  "> Everything above the `## Verdict` heading below is machine-generated by",
  "> `scripts/decile-momentum-study-pointintime-rerun.mts`. Re-running that script overwrites this",
  "> entire file with `writeFile`, including the `## Verdict` section — the script has no knowledge",
  "> that section exists. Do not re-run it after the verdict has been written; if the study needs to",
  "> be re-run, copy the verdict out first and reconcile it by hand afterward.",
  "",
  "## What changed from the 2026-08-16 run",
  "",
  "Nothing except the universe. The config (lookback, skip, buckets, seed, iterations, blocks), the",
  "six pre-registered gates and their thresholds, and the underlying price cache are all identical to",
  "`docs/quant/2026-08-16-cross-sectional-momentum-results.md`. The only difference: candidate",
  "selection in `buildSnapshots` is now gated on real point-in-time S&P 500 membership",
  "(`src/lib/backtest/crossSectional/membership.ts`) instead of applying today's S&P 500 list",
  "uniformly across the whole backtest history. This is a data-correctness re-run, not a re-cut of",
  "the hypothesis, using the same reasoning the original study used when it redid its first pass",
  "after finding unadjusted-split contamination in the cache — the original file and its written",
  "verdict are untouched.",
  "",
  "This fixes look-ahead inclusion (a symbol ranked as a candidate before it actually joined the",
  "index) and stale inclusion (a symbol kept ranking as a candidate after it actually left). It does",
  "**not** fix omission bias for names that left the S&P 500 before `.cache/bars/sp500-1d.json` was",
  "ever built — those tickers have no cached price history and cannot appear as candidates regardless",
  "of what the membership table says. Every number below remains an upper bound for that reason.",
  "",
  "## Data screen (stated before the results)",
  "",
  "Alpaca's `adjustment=all` is incomplete for recent splits, so the cache is screened rather than",
  "trusted — same screen as the original study. A symbol is excluded from the study entirely — not",
  "for one month — when any of these holds:",
  "",
  `1. its bars are spaced more than ${MAX_MEDIAN_SPACING_DAYS} calendar days apart at the median — i.e. it is not a daily series;`,
  `2. any close is zero or negative;`,
  `3. any adjacent-session close ratio falls outside [${MIN_DAILY_RATIO}, ${MAX_DAILY_RATIO}];`,
  `4. at least ${(MAX_ZERO_VOLUME_SHARE * 100).toFixed(0)}% of its bars have zero volume (a placeholder or reused-ticker series).`,
  "",
  `**${excluded.length} of ${cached.size} symbols excluded.**`,
  "",
  ...(excluded.length === 0
    ? ["_(none)_", ""]
    : [
        "| Symbol | Reason | Evidence |",
        "|---|---|---|",
        ...excluded.map((e) => `| ${e.symbol} | ${e.reason} | ${e.detail} |`),
        "",
      ]),
  "## Sample",
  "",
  `- symbols: ${bars.size}`,
  `- rebalances: **${full.snapshots.length}** (${iso(full.snapshots[0].day)} → ${iso(full.snapshots[full.snapshots.length - 1].day)})`,
  `- eligible per rebalance: min ${Math.min(...full.snapshots.map((s) => s.symbols.length))}, max ${Math.max(...full.snapshots.map((s) => s.symbols.length))}`,
  `- fill/exit substitutions: ${full.substitutions} (${pct(full.substitutions / full.snapshots.reduce((n, s) => n + s.symbols.length, 0))} of symbol-months)`,
  `- unfillable selections (dropped, no measurable return): ${full.unfillable}`,
  `- mega-cap subset: ${megaSymbols.size} symbols, ${mega.snapshots.length} rebalances`,
  `- config: lookback ${cfg.lookback}, skip ${cfg.skip}, buckets ${cfg.buckets}, seed ${cfg.seed}, ${cfg.iterations} permutations`,
  "",
];

for (const r of reports) {
  lines.push(
    `## Leg ${r.leg === "raw" ? "A — classic 12-1" : "B — volatility-adjusted"}`,
    "",
    `### Verdict: ${r.passed ? "**NOT REJECTED**" : "**REJECTED**"}`,
    "",
    "| # | Gate | Value | Threshold | Result |",
    "|---|---|---|---|---|",
    `| 1 | Monotonicity (Spearman ρ) | ${r.monotonicity.rho.toFixed(3)} | ≥ 0.60 | ${yn(r.monotonicity.pass)} |`,
    `| 2 | Permutation p | ${r.permutation.p.toFixed(4)} | ≤ 0.05 | ${yn(r.permutation.pass)} |`,
    `| 3 | Other leg's mean spread | ${pct(r.crossDefinition.otherMeanSpread)} | > 0 | ${yn(r.crossDefinition.pass)} |`,
    `| 4 | Bottom bucket vs universe ex-top | ${pct(r.notTopOnly.meanShortLegExcess)} | > 0 | ${yn(r.notTopOnly.pass)} |`,
    `| 5 | Mega-cap mean spread | ${pct(r.megaCap.meanSpread)} | > 0 | ${yn(r.megaCap.pass)} |`,
    `| 6 | Positive sub-periods | ${r.subPeriods.positive} of ${r.subPeriods.of} | ≥ 4 | ${yn(r.subPeriods.pass)} |`,
    "",
    "Reported, not gated:",
    "",
    `- mean monthly spread: **${pct(r.meanSpread)}** (net of 5 bps/side: ${pct(r.netMeanSpread)})`,
    `- t-statistic: **${r.tStat.toFixed(2)}** over ${r.months} months`,
    `- mean turnover per rebalance: ${pct(r.meanTurnover)}`,
    `- bucket means (1 = losers → ${cfg.buckets} = winners): ${r.bucketMeans.map((x) => pct(x)).join(", ")}`,
    `- sub-period means: ${r.subPeriods.blockMeans.map((x) => pct(x)).join(", ")}`,
    "",
  );
  console.log(`${r.leg}: ${r.passed ? "NOT REJECTED" : "REJECTED"}  rho=${r.monotonicity.rho.toFixed(3)} p=${r.permutation.p.toFixed(4)} spread=${pct(r.meanSpread)} t=${r.tStat.toFixed(2)}`);
}

lines.push(
  "## Reading these numbers",
  "",
  `At ${full.snapshots.length} monthly observations, \`t = 2\` requires an annual Sharpe near 0.90, while`,
  "published momentum decile spreads run 0.5-0.6 over far longer samples. The t-statistic above is",
  "therefore reported for reference and is not one of the gates.",
  "",
  "The universe is now point-in-time S&P 500 membership rather than today's list backfilled, which",
  "removes look-ahead inclusion and stale inclusion. It is still survivorship-biased toward names that",
  "have cached price history in the first place — see \"What changed\" above.",
  "",
  `The union calendar holds ${days.length} trading days. Of the ${bars.size} surviving symbols, ${lateStarts} have no bar on the`,
  `first day and ${earlyEnds} have none on the last. The fill/exit logic in buildSnapshots covers those,`,
  "and the unfillable count above is the number of selections that could not be measured at all.",
  "",
);

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, lines.join("\n"));
console.log(`\nwrote ${OUT}`);
